// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AG: typeof import('./src/components/Base/AG.vue')['default']
    GuideDrag: typeof import('./src/components/Base/GuideDrag.vue')['default']
    LogoWrapper: typeof import('./src/components/Base/LogoWrapper.vue')['default']
    MaskLayer: typeof import('./src/components/Base/MaskLayer.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
