// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LogoWrapper: typeof import('./src/components/Base/LogoWrapper.vue')['default']
    NLayout: typeof import('naive-ui')['NLayout']
  }
}

export {}
