name: CI

on:
  push:
    branches: feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'pnpm'
      # 检查缓存
      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: | 
            **/node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock')}}
      # 安装依赖
      - name: Install Dependence
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pnpm install
      # 执行任务
      - name: execute jobs
        run: pnpm run build
  # 部署 github pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Checkout repo
        uses: actions/checkout@v2
      # - name: download build files
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: build-pages
      #     path: app/main/dist
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # 部署的分支名 有一定要独立一个分支，第一次设置为master 好家伙构建完成后，直接把我的项目文件清除了，只剩下打包的文件了。
          folder: ../app/main/dist   # build后文件目录